from examples.debussy.childrens_corner_1 import childrens_corner_1
from examples.debussy.childrens_corner_2 import childrens_corner_2
from examples.debussy.childrens_corner_3 import childrens_corner_3
from examples.debussy.childrens_corner_4 import childrens_corner_4
from examples.debussy.childrens_corner_5 import childrens_corner_5
from examples.debussy.claire_de_lune import claire_de_lune
from examples.debussy.menuet import menuet
from examples.debussy.passepied import passepied
from examples.debussy.prelude import prelude
